"""initial schema

Revision ID: 2b362424ff94
Revises: 
Create Date: 2026-10-06 21:45:47.935883
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '2b362424ff94'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('devices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_code', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('firmware_version', sa.String(length=30), nullable=True),
    sa.Column('hardware_version', sa.String(length=30), nullable=True),
    sa.Column('location', sa.String(length=120), nullable=True),
    sa.Column('last_seen_online', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('inactive', 'active', 'maintenance', 'retired')", name='ck_devices_status'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_devices_device_code'), 'devices', ['device_code'], unique=True)
    op.create_index(op.f('ix_devices_status'), 'devices', ['status'], unique=False)
    op.create_table('patients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_code', sa.String(length=20), nullable=False),
    sa.Column('sex', sa.String(length=1), nullable=True),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('gestational_age_weeks', sa.SmallInteger(), nullable=True),
    sa.Column('birth_weight_kg', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patients_patient_code'), 'patients', ['patient_code'], unique=True)
    op.create_table('thresholds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parameter', sa.String(length=40), nullable=False),
    sa.Column('value', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('source', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('effective_from', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('parameter', 'version', name='uq_threshold_parameter_version')
    )
    op.create_index(op.f('ix_thresholds_parameter'), 'thresholds', ['parameter'], unique=False)
    op.create_index('uq_active_threshold_parameter', 'thresholds', ['parameter'], unique=True, postgresql_where=sa.text('is_active = true'))
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("role IN ('admin', 'nurse', 'clinician')", name='ck_users_role'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=60), nullable=False),
    sa.Column('resource_type', sa.String(length=50), nullable=True),
    sa.Column('resource_id', sa.Integer(), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_log_action'), 'audit_log', ['action'], unique=False)
    op.create_index(op.f('ix_audit_log_created_at'), 'audit_log', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_log_user_id'), 'audit_log', ['user_id'], unique=False)
    op.create_table('dataset_imports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dataset_key', sa.String(length=80), nullable=False),
    sa.Column('archive_name', sa.String(length=255), nullable=False),
    sa.Column('member_name', sa.String(length=255), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('schema_version', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('source_reference', sa.Text(), nullable=True),
    sa.Column('rows_seen', sa.Integer(), nullable=False),
    sa.Column('rows_accepted', sa.Integer(), nullable=False),
    sa.Column('rows_rejected', sa.Integer(), nullable=False),
    sa.Column('notes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('imported_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('received', 'review', 'imported', 'rejected')", name='ck_dataset_import_status'),
    sa.CheckConstraint('rows_seen >= 0 AND rows_accepted >= 0 AND rows_rejected >= 0', name='ck_dataset_import_counts'),
    sa.ForeignKeyConstraint(['imported_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dataset_key', 'sha256', name='uq_dataset_import_file')
    )
    op.create_index(op.f('ix_dataset_imports_dataset_key'), 'dataset_imports', ['dataset_key'], unique=False)
    op.create_index(op.f('ix_dataset_imports_status'), 'dataset_imports', ['status'], unique=False)
    op.create_table('device_components',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('component_type', sa.String(length=50), nullable=False),
    sa.Column('pin_or_address', sa.String(length=50), nullable=True),
    sa.Column('is_critical', sa.Boolean(), nullable=False),
    sa.Column('installed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('device_id', 'component_type', name='uq_device_component_type')
    )
    op.create_index(op.f('ix_device_components_device_id'), 'device_components', ['device_id'], unique=False)
    op.create_table('device_credentials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('secret_hash', sa.String(length=64), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('device_id'),
    sa.UniqueConstraint('secret_hash')
    )
    op.create_table('device_telemetry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('reported_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('battery_percent', sa.SmallInteger(), nullable=True),
    sa.Column('wifi_rssi_dbm', sa.SmallInteger(), nullable=True),
    sa.Column('uptime_seconds', sa.Integer(), nullable=True),
    sa.CheckConstraint('battery_percent IS NULL OR battery_percent BETWEEN 0 AND 100', name='ck_battery_percent'),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_device_telemetry_device_id'), 'device_telemetry', ['device_id'], unique=False)
    op.create_index('ix_telemetry_device_reported', 'device_telemetry', ['device_id', 'reported_at'], unique=False)
    op.create_table('monitoring_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('started_by_user_id', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.CheckConstraint("(status = 'active' AND ended_at IS NULL) OR (status <> 'active' AND ended_at IS NOT NULL)", name='ck_session_end_time'),
    sa.CheckConstraint("status IN ('active', 'completed', 'stopped')", name='ck_session_status'),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['started_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_monitoring_sessions_device_id'), 'monitoring_sessions', ['device_id'], unique=False)
    op.create_index(op.f('ix_monitoring_sessions_patient_id'), 'monitoring_sessions', ['patient_id'], unique=False)
    op.create_index(op.f('ix_monitoring_sessions_status'), 'monitoring_sessions', ['status'], unique=False)
    op.create_index('uq_active_session_device', 'monitoring_sessions', ['device_id'], unique=True, postgresql_where=sa.text("status = 'active'"))
    op.create_index('uq_active_session_patient', 'monitoring_sessions', ['patient_id'], unique=True, postgresql_where=sa.text("status = 'active'"))
    op.create_table('risk_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('low_birth_weight', sa.Boolean(), nullable=True),
    sa.Column('prematurity', sa.Boolean(), nullable=True),
    sa.Column('home_birth', sa.Boolean(), nullable=True),
    sa.Column('delayed_breastfeeding', sa.Boolean(), nullable=True),
    sa.Column('skin_to_skin', sa.Boolean(), nullable=True),
    sa.Column('socioeconomic_status', sa.String(length=20), nullable=True),
    sa.Column('other_factors', sa.JSON(), nullable=True),
    sa.Column('updated_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('patient_id')
    )
    op.create_table('component_health_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('component_id', sa.Integer(), nullable=False),
    sa.Column('checked_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('error_code', sa.String(length=50), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['component_id'], ['device_components.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_component_health_logs_component_id'), 'component_health_logs', ['component_id'], unique=False)
    op.create_index(op.f('ix_component_health_logs_device_id'), 'component_health_logs', ['device_id'], unique=False)
    op.create_table('dataset_import_rows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dataset_import_id', sa.Integer(), nullable=False),
    sa.Column('source_row_number', sa.Integer(), nullable=False),
    sa.Column('external_subject_id', sa.String(length=100), nullable=True),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('validation_status', sa.String(length=20), nullable=False),
    sa.Column('quality_flags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('review_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("validation_status IN ('pending', 'accepted', 'rejected', 'review')", name='ck_dataset_row_status'),
    sa.CheckConstraint('source_row_number > 0', name='ck_dataset_source_row_positive'),
    sa.ForeignKeyConstraint(['dataset_import_id'], ['dataset_imports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dataset_import_id', 'source_row_number', name='uq_dataset_import_source_row')
    )
    op.create_index(op.f('ix_dataset_import_rows_dataset_import_id'), 'dataset_import_rows', ['dataset_import_id'], unique=False)
    op.create_index(op.f('ix_dataset_import_rows_external_subject_id'), 'dataset_import_rows', ['external_subject_id'], unique=False)
    op.create_index(op.f('ix_dataset_import_rows_validation_status'), 'dataset_import_rows', ['validation_status'], unique=False)
    op.create_table('dataset_subjects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dataset_import_id', sa.Integer(), nullable=False),
    sa.Column('external_subject_id', sa.String(length=100), nullable=False),
    sa.Column('sex', sa.String(length=1), nullable=True),
    sa.Column('gestational_age_weeks', sa.Numeric(precision=4, scale=1), nullable=True),
    sa.Column('birth_weight_kg', sa.Numeric(precision=5, scale=3), nullable=True),
    sa.Column('birth_length_cm', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('birth_head_circumference_cm', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('apgar_score', sa.Numeric(precision=3, scale=1), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['dataset_import_id'], ['dataset_imports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dataset_import_id', 'external_subject_id', name='uq_dataset_subject_external_id'),
    sa.UniqueConstraint('dataset_import_id', 'id', name='uq_dataset_subject_import_id')
    )
    op.create_index(op.f('ix_dataset_subjects_dataset_import_id'), 'dataset_subjects', ['dataset_import_id'], unique=False)
    op.create_table('readings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('device_event_id', sa.Uuid(), nullable=False),
    sa.Column('measured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('heart_rate_bpm', sa.SmallInteger(), nullable=True),
    sa.Column('spo2_percent', sa.SmallInteger(), nullable=True),
    sa.Column('temperature_c', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('quality', sa.String(length=30), nullable=False),
    sa.CheckConstraint('heart_rate_bpm IS NOT NULL OR spo2_percent IS NOT NULL OR temperature_c IS NOT NULL', name='ck_reading_has_measurement'),
    sa.CheckConstraint('heart_rate_bpm IS NULL OR heart_rate_bpm BETWEEN 40 AND 220', name='ck_reading_hr'),
    sa.CheckConstraint('spo2_percent IS NULL OR spo2_percent BETWEEN 50 AND 100', name='ck_reading_spo2'),
    sa.CheckConstraint('temperature_c IS NULL OR temperature_c BETWEEN 30 AND 42', name='ck_reading_temp'),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['session_id'], ['monitoring_sessions.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('device_id', 'device_event_id', name='uq_reading_device_event')
    )
    op.create_index(op.f('ix_readings_device_id'), 'readings', ['device_id'], unique=False)
    op.create_index(op.f('ix_readings_measured_at'), 'readings', ['measured_at'], unique=False)
    op.create_index(op.f('ix_readings_session_id'), 'readings', ['session_id'], unique=False)
    op.create_index('ix_readings_session_measured', 'readings', ['session_id', 'measured_at'], unique=False)
    op.create_table('alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('reading_id', sa.Integer(), nullable=True),
    sa.Column('alert_type', sa.String(length=30), nullable=False),
    sa.Column('parameter', sa.String(length=30), nullable=True),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('acknowledged_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("severity IN ('low', 'medium', 'high', 'critical')", name='ck_alert_severity'),
    sa.ForeignKeyConstraint(['acknowledged_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['reading_id'], ['readings.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['session_id'], ['monitoring_sessions.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reading_id', 'alert_type', 'parameter', name='uq_alert_per_reading_rule')
    )
    op.create_index('ix_alerts_ack_created', 'alerts', ['acknowledged_at', 'created_at'], unique=False)
    op.create_index(op.f('ix_alerts_acknowledged_at'), 'alerts', ['acknowledged_at'], unique=False)
    op.create_index(op.f('ix_alerts_reading_id'), 'alerts', ['reading_id'], unique=False)
    op.create_index(op.f('ix_alerts_session_id'), 'alerts', ['session_id'], unique=False)
    op.create_index(op.f('ix_alerts_severity'), 'alerts', ['severity'], unique=False)
    op.create_table('dataset_observations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dataset_import_id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('source_row_number', sa.Integer(), nullable=False),
    sa.Column('observed_on', sa.Date(), nullable=True),
    sa.Column('age_days', sa.SmallInteger(), nullable=True),
    sa.Column('weight_kg', sa.Numeric(precision=5, scale=3), nullable=True),
    sa.Column('length_cm', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('head_circumference_cm', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('temperature_c', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('heart_rate_bpm', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('respiratory_rate_bpm', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('spo2_percent', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('feeding_type', sa.String(length=40), nullable=True),
    sa.Column('feeding_frequency_per_day', sa.SmallInteger(), nullable=True),
    sa.Column('urine_output_count', sa.SmallInteger(), nullable=True),
    sa.Column('stool_count', sa.SmallInteger(), nullable=True),
    sa.Column('jaundice_level_mg_dl', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('immunizations_done', sa.Boolean(), nullable=True),
    sa.Column('reflexes_normal', sa.Boolean(), nullable=True),
    sa.Column('imported_risk_label', sa.String(length=80), nullable=True),
    sa.Column('quality_flags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['dataset_import_id', 'subject_id'], ['dataset_subjects.dataset_import_id', 'dataset_subjects.id'], name='fk_dataset_observation_same_import_subject', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['dataset_import_id'], ['dataset_imports.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subject_id'], ['dataset_subjects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dataset_import_id', 'source_row_number', name='uq_dataset_observation_source_row')
    )
    op.create_index('ix_dataset_observation_subject_date', 'dataset_observations', ['subject_id', 'observed_on'], unique=False)
    op.create_index(op.f('ix_dataset_observations_dataset_import_id'), 'dataset_observations', ['dataset_import_id'], unique=False)
    op.create_index(op.f('ix_dataset_observations_observed_on'), 'dataset_observations', ['observed_on'], unique=False)
    op.create_index(op.f('ix_dataset_observations_subject_id'), 'dataset_observations', ['subject_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_dataset_observations_subject_id'), table_name='dataset_observations')
    op.drop_index(op.f('ix_dataset_observations_observed_on'), table_name='dataset_observations')
    op.drop_index(op.f('ix_dataset_observations_dataset_import_id'), table_name='dataset_observations')
    op.drop_index('ix_dataset_observation_subject_date', table_name='dataset_observations')
    op.drop_table('dataset_observations')
    op.drop_index(op.f('ix_alerts_severity'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_session_id'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_reading_id'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_acknowledged_at'), table_name='alerts')
    op.drop_index('ix_alerts_ack_created', table_name='alerts')
    op.drop_table('alerts')
    op.drop_index('ix_readings_session_measured', table_name='readings')
    op.drop_index(op.f('ix_readings_session_id'), table_name='readings')
    op.drop_index(op.f('ix_readings_measured_at'), table_name='readings')
    op.drop_index(op.f('ix_readings_device_id'), table_name='readings')
    op.drop_table('readings')
    op.drop_index(op.f('ix_dataset_subjects_dataset_import_id'), table_name='dataset_subjects')
    op.drop_table('dataset_subjects')
    op.drop_index(op.f('ix_dataset_import_rows_validation_status'), table_name='dataset_import_rows')
    op.drop_index(op.f('ix_dataset_import_rows_external_subject_id'), table_name='dataset_import_rows')
    op.drop_index(op.f('ix_dataset_import_rows_dataset_import_id'), table_name='dataset_import_rows')
    op.drop_table('dataset_import_rows')
    op.drop_index(op.f('ix_component_health_logs_device_id'), table_name='component_health_logs')
    op.drop_index(op.f('ix_component_health_logs_component_id'), table_name='component_health_logs')
    op.drop_table('component_health_logs')
    op.drop_table('risk_profiles')
    op.drop_index('uq_active_session_patient', table_name='monitoring_sessions', postgresql_where=sa.text("status = 'active'"))
    op.drop_index('uq_active_session_device', table_name='monitoring_sessions', postgresql_where=sa.text("status = 'active'"))
    op.drop_index(op.f('ix_monitoring_sessions_status'), table_name='monitoring_sessions')
    op.drop_index(op.f('ix_monitoring_sessions_patient_id'), table_name='monitoring_sessions')
    op.drop_index(op.f('ix_monitoring_sessions_device_id'), table_name='monitoring_sessions')
    op.drop_table('monitoring_sessions')
    op.drop_index('ix_telemetry_device_reported', table_name='device_telemetry')
    op.drop_index(op.f('ix_device_telemetry_device_id'), table_name='device_telemetry')
    op.drop_table('device_telemetry')
    op.drop_table('device_credentials')
    op.drop_index(op.f('ix_device_components_device_id'), table_name='device_components')
    op.drop_table('device_components')
    op.drop_index(op.f('ix_dataset_imports_status'), table_name='dataset_imports')
    op.drop_index(op.f('ix_dataset_imports_dataset_key'), table_name='dataset_imports')
    op.drop_table('dataset_imports')
    op.drop_index(op.f('ix_audit_log_user_id'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_created_at'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_action'), table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index('uq_active_threshold_parameter', table_name='thresholds', postgresql_where=sa.text('is_active = true'))
    op.drop_index(op.f('ix_thresholds_parameter'), table_name='thresholds')
    op.drop_table('thresholds')
    op.drop_index(op.f('ix_patients_patient_code'), table_name='patients')
    op.drop_table('patients')
    op.drop_index(op.f('ix_devices_status'), table_name='devices')
    op.drop_index(op.f('ix_devices_device_code'), table_name='devices')
    op.drop_table('devices')
    # ### end Alembic commands ###
