"""secure sync and AI data foundations

Revision ID: dfa649bdd60b
Revises: 2b362424ff94
Create Date: 2026-10-06 22:19:09.161184
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = 'dfa649bdd60b'
down_revision = '2b362424ff94'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('login_failures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('identifier_hash', sa.String(length=64), nullable=False),
    sa.Column('source_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_login_failures_created_at'), 'login_failures', ['created_at'], unique=False)
    op.create_index(op.f('ix_login_failures_identifier_hash'), 'login_failures', ['identifier_hash'], unique=False)
    op.create_index(op.f('ix_login_failures_source_hash'), 'login_failures', ['source_hash'], unique=False)
    op.create_table('model_registry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model_key', sa.String(length=80), nullable=False),
    sa.Column('version', sa.String(length=40), nullable=False),
    sa.Column('task_type', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('artifact_uri', sa.Text(), nullable=True),
    sa.Column('artifact_sha256', sa.String(length=64), nullable=True),
    sa.Column('training_dataset_import_id', sa.Integer(), nullable=True),
    sa.Column('metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('validation_notes', sa.Text(), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('candidate', 'approved', 'retired')", name='ck_model_registry_status'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['training_dataset_import_id'], ['dataset_imports.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('model_key', 'version', name='uq_model_key_version')
    )
    op.create_index(op.f('ix_model_registry_model_key'), 'model_registry', ['model_key'], unique=False)
    op.create_index(op.f('ix_model_registry_status'), 'model_registry', ['status'], unique=False)
    op.create_index(op.f('ix_model_registry_training_dataset_import_id'), 'model_registry', ['training_dataset_import_id'], unique=False)
    op.create_table('outcome_labels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=True),
    sa.Column('dataset_subject_id', sa.Integer(), nullable=True),
    sa.Column('target', sa.String(length=80), nullable=False),
    sa.Column('label_value', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('source', sa.String(length=200), nullable=False),
    sa.Column('evidence_reference', sa.Text(), nullable=True),
    sa.Column('observed_from', sa.DateTime(timezone=True), nullable=True),
    sa.Column('observed_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('review_status', sa.String(length=20), nullable=False),
    sa.Column('reviewed_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("review_status IN ('unreviewed', 'confirmed', 'rejected')", name='ck_outcome_label_review_status'),
    sa.CheckConstraint('(patient_id IS NOT NULL AND dataset_subject_id IS NULL) OR (patient_id IS NULL AND dataset_subject_id IS NOT NULL)', name='ck_outcome_label_exactly_one_subject'),
    sa.CheckConstraint('observed_from IS NULL OR observed_to IS NULL OR observed_from <= observed_to', name='ck_outcome_label_window'),
    sa.ForeignKeyConstraint(['dataset_subject_id'], ['dataset_subjects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewed_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_outcome_labels_dataset_subject_id'), 'outcome_labels', ['dataset_subject_id'], unique=False)
    op.create_index(op.f('ix_outcome_labels_patient_id'), 'outcome_labels', ['patient_id'], unique=False)
    op.create_index(op.f('ix_outcome_labels_review_status'), 'outcome_labels', ['review_status'], unique=False)
    op.create_index(op.f('ix_outcome_labels_target'), 'outcome_labels', ['target'], unique=False)
    op.create_table('risk_scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=True),
    sa.Column('model_registry_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Numeric(precision=6, scale=5), nullable=False),
    sa.Column('risk_category', sa.String(length=20), nullable=False),
    sa.Column('target', sa.String(length=80), nullable=False),
    sa.Column('data_window_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('data_window_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('feature_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('explanation', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('computed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("risk_category IN ('low', 'moderate', 'high', 'critical')", name='ck_risk_score_category'),
    sa.CheckConstraint('data_window_start IS NULL OR data_window_end IS NULL OR data_window_start <= data_window_end', name='ck_risk_score_window'),
    sa.CheckConstraint('score >= 0 AND score <= 1', name='ck_risk_score_range'),
    sa.ForeignKeyConstraint(['model_registry_id'], ['model_registry.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['session_id'], ['monitoring_sessions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_risk_scores_computed_at'), 'risk_scores', ['computed_at'], unique=False)
    op.create_index(op.f('ix_risk_scores_model_registry_id'), 'risk_scores', ['model_registry_id'], unique=False)
    op.create_index(op.f('ix_risk_scores_patient_id'), 'risk_scores', ['patient_id'], unique=False)
    op.create_index(op.f('ix_risk_scores_session_id'), 'risk_scores', ['session_id'], unique=False)
    op.add_column('devices', sa.Column('last_sync_received_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('devices', 'last_sync_received_at')
    op.drop_index(op.f('ix_risk_scores_session_id'), table_name='risk_scores')
    op.drop_index(op.f('ix_risk_scores_patient_id'), table_name='risk_scores')
    op.drop_index(op.f('ix_risk_scores_model_registry_id'), table_name='risk_scores')
    op.drop_index(op.f('ix_risk_scores_computed_at'), table_name='risk_scores')
    op.drop_table('risk_scores')
    op.drop_index(op.f('ix_outcome_labels_target'), table_name='outcome_labels')
    op.drop_index(op.f('ix_outcome_labels_review_status'), table_name='outcome_labels')
    op.drop_index(op.f('ix_outcome_labels_patient_id'), table_name='outcome_labels')
    op.drop_index(op.f('ix_outcome_labels_dataset_subject_id'), table_name='outcome_labels')
    op.drop_table('outcome_labels')
    op.drop_index(op.f('ix_model_registry_training_dataset_import_id'), table_name='model_registry')
    op.drop_index(op.f('ix_model_registry_status'), table_name='model_registry')
    op.drop_index(op.f('ix_model_registry_model_key'), table_name='model_registry')
    op.drop_table('model_registry')
    op.drop_index(op.f('ix_login_failures_source_hash'), table_name='login_failures')
    op.drop_index(op.f('ix_login_failures_identifier_hash'), table_name='login_failures')
    op.drop_index(op.f('ix_login_failures_created_at'), table_name='login_failures')
    op.drop_table('login_failures')
    # ### end Alembic commands ###
