"""enforce score patient session integrity

Revision ID: e489b65cfe50
Revises: dfa649bdd60b
Create Date: 2026-10-06 22:25:21.229417
"""
from alembic import op
import sqlalchemy as sa


revision = 'e489b65cfe50'
down_revision = 'dfa649bdd60b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_session_patient_id', 'monitoring_sessions', ['patient_id', 'id'])
    op.drop_constraint(op.f('risk_scores_session_id_fkey'), 'risk_scores', type_='foreignkey')
    op.create_foreign_key('fk_risk_score_patient_session', 'risk_scores', 'monitoring_sessions', ['patient_id', 'session_id'], ['patient_id', 'id'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_risk_score_patient_session', 'risk_scores', type_='foreignkey')
    op.create_foreign_key(op.f('risk_scores_session_id_fkey'), 'risk_scores', 'monitoring_sessions', ['session_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint('uq_session_patient_id', 'monitoring_sessions', type_='unique')
    # ### end Alembic commands ###
